language: c
branches:
  only: master
before_install:
  - wget https://github.com/njanetos/narchiver-processor/raw/master/raw_zipped_test.zip
script: make sense
notifications:
  email:
    on_success: change
    on_failure: change

