language: c
branches:
  only: master
before_install:
  - rm -rf raw_zipped_test.zip
  - wget https://github.com/njanetos/narchiver-processor/raw/master/raw_zipped_test.zip
  - pip install lxml
script: make sense
notifications:
  email:
    on_success: change
    on_failure: change
