language: c
branches:
  only: master
addons:
  apt:
    packages:
    - r-base
    - python-lxml
    - python-requests
    - python-dateutil
before_install:
  - mkdir logs
  - rm -rf raw_zipped_test.zip
  - wget https://github.com/njanetos/narchiver-processor/raw/master/raw_zipped_test.zip
script: make aggregate_listings
notifications:
  email:
    on_success: change
    on_failure: change
