---
title: "Dark net marketplaces: The Agora marketplace"
author: "Nick Janetos"
date: "November 15, 2015"
output: html_document
---

Statistical analysis of the Agora marketplace.

```{r packages, cache=FALSE, echo=FALSE, include=FALSE, message=FALSE}
# Load all the packages
list.of.packages <- c("sqldf", "data.table", "plm", "texreg", "pastecs", "pander")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos="http://cran.rstudio.com/")

for (p in list.of.packages) {
    library(p, character.only = TRUE)
}

args <- commandArgs(trailingOnly = TRUE)

if (length(args) > 0) {
    market = args[1]
} else {
    market = "agora"
}

path = paste(getwd(), "/../combined_market/", market, ".db", sep = "")

```

```{r preliminary, echo=FALSE}
prices_ = sqldf("SELECT * FROM prices AS p JOIN listings AS l ON l.rowid == p.listing JOIN categories AS c ON c.rowid == l.category", dbname = path)
prices_$log_price = log(prices_$price)
prices_ = subset(prices_, select = c(dat, listing, vendor, price, rating, sales, category, log_price))
vendors_ = sqldf("SELECT * FROM vendors", dbname = path)
categories_ = sqldf("SELECT * FROM categories", dbname = path)
prices_ = prices_[prices_$rating <= 5 & prices_$rating >= 0 & prices_$sales >= 0, ]
prices_ = prices_[order(prices_$vendor, prices_$listing, prices_$dat), ]
prices_ = prices_[c(2, 1, 3, 4, 5, 6, 7, 8)]
prices_$dat = prices_$dat/86400
```

# Data description and descriptive statistics

## Data

```{r echo=FALSE}
panderOptions("digits", 2)
panderOptions("table.style", "rmarkdown")
panderOptions("table.split.table", Inf)
```

### Descriptive statistics:

```{r descriptive, echo=FALSE, cache=TRUE, warning=FALSE}
pander(stat.desc(prices_))
```

### Histogram of ratings

```{r hist, cache=TRUE, echo=FALSE} 
hist(prices_$rating[prices_$rating > 0])
```

```{r hist2, cache=TRUE, echo=FALSE} 
hist(prices_$rating[prices_$rating > 4.4])
```

# Reduced form estimates

### Panel regression

```{r plm, cache=TRUE, echo=FALSE, warning=FALSE}
interesting_categories = c(2, 3, 4, 6, 7, 8, 19, 21, 24, 26, 27, 28, 29, 30, 31, 33, 35, 39, 45, 50, 57, 71, 94, 95, 97, 106)
temp_prices = subset(prices_, select = c(dat, listing, rating, sales, log_price, category, vendor))
sink("test.log")
for (i in interesting_categories) {
    prices_plm = pdata.frame(subset(temp_prices[temp_prices$category == i,], select = -c(category)), c("listing", "dat"), drop.index = TRUE, row.names = TRUE)
    print(paste("Category", categories_[i,]))
    print(summary(plm(log_price ~ rating + sales + rating*sales, data=prices_plm, model="random")))
    cat("\n\n\n")
}
```